// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"github.com/alexsandroveiga/redis-like-golang/internal/adapter/handler"
	"github.com/alexsandroveiga/redis-like-golang/internal/adapter/protocol"
	"github.com/alexsandroveiga/redis-like-golang/internal/infra/persistence"
	"github.com/alexsandroveiga/redis-like-golang/internal/infra/storage"
	"github.com/alexsandroveiga/redis-like-golang/internal/usecase"
)

// Injectors from wire.go:

func InitializeContainer(opt persistence.AOFProviderOption) (*Container, func(), error) {
	keyValueRepository := storage.NewStore()
	persistenceRepository, err := persistence.NewAOFProvider(opt)
	if err != nil {
		return nil, nil, err
	}
	parser := protocol.NewParser()
	stats := usecase.NewStats(keyValueRepository)
	commandHandler := usecase.NewCommandHandler(parser, keyValueRepository, persistenceRepository, stats)
	tcpHandler := handler.NewTCPHandler(commandHandler, parser)
	container := NewContainer(keyValueRepository, persistenceRepository, commandHandler, tcpHandler, parser)
	return container, func() {
	}, nil
}
